    @ Peripheral identifiers register 0
    .equ        PERIPHERAL_0_SUPC, 0
    .equ        PERIPHERAL_0_RSTC, 1
    .equ        PERIPHERAL_0_RTC, 2
    .equ        PERIPHERAL_0_RTT, 3
    .equ        PERIPHERAL_0_WDT, 4
    .equ        PERIPHERAL_0_PMC, 5
    .equ        PERIPHERAL_0_EEFC, 6
    .equ        PERIPHERAL_0_UART0, 8
    .equ        PERIPHERAL_0_UART1, 9
    .equ        PERIPHERAL_0_SMC, 10
    .equ        PERIPHERAL_0_PIOA, 11
    .equ        PERIPHERAL_0_PIOB, 12
    .equ        PERIPHERAL_0_PIOC, 13
    .equ        PERIPHERAL_0_USART0, 14
    .equ        PERIPHERAL_0_USART1, 15
    .equ        PERIPHERAL_0_HSMCI, 18
    .equ        PERIPHERAL_0_TWI0, 19
    .equ        PERIPHERAL_0_TWI1, 20
    .equ        PERIPHERAL_0_SPI, 21
    .equ        PERIPHERAL_0_SSC, 22
    .equ        PERIPHERAL_0_TC0, 23
    .equ        PERIPHERAL_0_TC1, 24
    .equ        PERIPHERAL_0_TC2, 25
    .equ        PERIPHERAL_0_TC3, 26
    .equ        PERIPHERAL_0_TC4, 27
    .equ        PERIPHERAL_0_TC5, 28
    .equ        PERIPHERAL_0_ADC, 29
    .equ        PERIPHERAL_0_DACC, 30
    .equ        PERIPHERAL_0_PWM, 31
    .equ        PERIPHERAL_1_CRCCU, 0   @ ID = 32 - 32
    .equ        PERIPHERAL_1_ACC, 1     @ ID = 33 - 32
    .equ        PERIPHERAL_1_UDP, 2     @ ID = 34 - 32
